### ISSUE TITLE
livox驱动数据时间戳咨询

### ISSUE THREAD

**Issue by MengHuiLei** [xuankuzcr/Handheld_ws#3]
@xuankuzcr 
    请允许我先感谢您开源这么好的项目！！！！ 膜拜大佬。。。。
    想复现fast_livo的效果，测试时遇到一点问题，想向您咨询一下。
    前提：
      1. 采用[Handheld_ws](https://github.com/xuankuzcr/Handheld_ws)这里的时间同步器，稳定发布1Hz和10HzPPS信号源。
     2. 相机：mv-cs050-10gc-pro，雷达：horizon，采用千兆交换机与笔记本相连；
     3. 确定相机和雷达均能收到PPS信号；
   不同点：
     1. 由于相机的接口方式不同，故未能采用Handheld_ws中的相机驱动，但同样采用 接收到相机数据的时间 赋值 相机话题的时间；
   
   出现的问题：采用Handheld_ws中的livox_ros_driver和时间同步器，发现相机和雷达的时间对应不上 且 雷达的时间较为滞后。
   如图：图中左侧为传感器发布的时间，右侧为系统时间

![2023-04-26 15-22-47屏幕截图](https://user-images.githubusercontent.com/43312769/234787476-2454d4f1-3b69-4552-a169-6d1635fd9fee.png)

**Comment by MengHuiLei** [comment]
另外该livox_ros_driver在pps模式下，fast-lio建图失败。

**Comment by MengHuiLei** [comment]
已解决

**Comment by hshong-nuaa** [comment]
@MengHuiLei 您好，请问您是怎么解决时间戳延迟问题的，我测试了mid70与海康相机时间同步，但是时间延迟总有20ms左右

**Comment by MengHuiLei** [comment]
不好意思哈！！ 最近在忙项目，回复晚了！！
说实话，我这个也存在延迟20ms左右的延迟，如下图；
建图效果还可以，就没有再关注这个问题。
![img_v3_025e_59c6dcad-ffa4-43ed-8609-6602588dc10g](https://github.com/xuankuzcr/Handheld_ws/assets/43312769/2de074fc-cf91-41b2-8af9-40183d831717)
